<?php
date_default_timezone_set('Asia/Kolkata');
?>

<!DOCTYPE html>
<html>

<head>
    <meta charset='UTF-8'>
</head>

<body style='margin:0; padding:30px; background:#f4f7fb; font-family:Arial, Helvetica, sans-serif;'>

    <table width='100%' cellpadding='0' cellspacing='0'>
        <tr>
            <td align='center'>

                <table width='600' cellpadding='0' cellspacing='0'
                    style='background:#ffffff; border-radius:12px; overflow:hidden; box-shadow:0 8px 30px rgba(0,0,0,.08);'>

                    <!-- Header -->
                    <tr>
                        <td
                            style='background:linear-gradient(90deg,#22d3ee,#a855f7); padding:24px; text-align:center; color:#ffffff;'>
                            <h1 style='margin:0; font-size:28px;'>IndoSparsh Studio</h1>
                            <p style='margin:8px 0 0;'>New Newsletter Subscription</p>
                        </td>
                    </tr>

                    <!-- Content -->
                    <tr>
                        <td style='padding:30px;'>

                            <h2 style='margin-top:0; color:#222;'>
                                🎉 Someone subscribed to your website!
                            </h2>

                            <p style='color:#555; line-height:1.7;'>
                                A visitor has successfully subscribed through your website.
                                You can reach out to them using the email address below.
                            </p>

                            <table width='100%' cellpadding='12'
                                style='margin:25px 0; border:1px solid #e5e7eb; border-radius:8px; background:#f9fafb;'>

                                <tr>
                                    <td width='140'><strong>Email Address</strong></td>
                                    <td><?= htmlspecialchars($email) ?></td>
                                </tr>

                                <tr>
                                    <td><strong>Subscribed On</strong></td>
                                    <td><?= date('F j, Y \a\t g:i A') ?></td>
                                </tr>
                        </td>
                    </tr>

                </table>

                <div style='text-align:center; margin-top:30px;'>
                    <a href='mailto:{$email}' style='display:inline-block;
                                          padding:14px 30px;
                                          background:#22d3ee;
                                          color:#ffffff;
                                          text-decoration:none;
                                          border-radius:8px;
                                          font-weight:bold;'>
                        Contact Subscriber
                    </a>
                </div>

            </td>
        </tr>

        <!-- Footer -->
        <tr>
            <td style='padding:20px; text-align:center; background:#f9fafb; color:#888; font-size:13px;'>
                This notification was automatically generated by
                <strong>IndoSparsh Studio</strong>.
                <br><br>
                © <?= date('Y') ?> IndoSparsh Studio. All rights reserved.
            </td>
        </tr>

    </table>

    </td>
    </tr>
    </table>

</body>

</html>