export const services = [
  "Website Development",
  "Landing Page",
  "E-commerce Website",
  "Portfolio Website",
  "Web Application",
  "UI/UX Design",
  "Website Redesign",
  "Maintenance & Support",
  "SEO Optimization",
  "Other",
];

export const budget = [
  "Below ₹10,000",
  "₹10,000 - ₹25,000",
  "₹25,000 - ₹50,000",
  "₹50,000 - ₹1,00,000",
  "₹1,00,000+",
];

export const timeLine = [
  "ASAP",
  "Within 1 Week",
  "Within 2 Weeks",
  "Within 1 Month",
  "1–3 Months",
  "Flexible",
];

export const countries = [
  "India",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",

  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const preferedContactMethod = ["Email", "Phone", "Whatsapp"];

export const footerServices = [
  { name: "Website Development", path: "/services/website-development" },
  { name: "App Development", path: "/services/app-development" },
  { name: "Landing Page", path: "/services/landing-page" },
  { name: "E-commerce Website", path: "/services/ecommerce-website" },
  { name: "Portfolio Website", path: "/services/portfolio-website" },
  { name: "Web Application", path: "/services/web-application" },
  { name: "UI/UX Design", path: "/services/ui-ux-design" },
  { name: "Website Redesign", path: "/services/website-redesign" },
  { name: "Content creation & video editing", path: "/services/content-hub" }, 

  { name: "SEO Optimization", path: "/services/seo-optimization" },
  { name: "Business Profile Creation", path: "/services/profile-creation" }, 
  { name: "Digital Marketing Services", path: "/services/digital-marketing" }, 
   { name: "Social media management", path: "/services/social-media" }, 
  { name: "Maintenance & Support", path: "/services/maintenance-support" },

  { name: "Branding and marketing", path: "/services/branding-marketing" }, 
  { name: "Business Consultancy", path: "/services/business-consultancy" }, 
  { name: "Graphic Designing", path: "/services/graphic-design" }, 
  { name: "Row Calling data", path: "/services/row-calling-data" }, 
  { name: "Other", path: "/services" },
];

export const companies = [
  { name: "Home", path: "/" },
  { name: "About", path: "/about" },
  { name: "Services", path: "/services" },
  { name: "Blogs", path: "/blogs" },
  { name: "Contact", path: "/contact" },
  { name: "Career", path: "/career" },
];

export const supports = [
  { name: "Request a Quote", path: "/request-quote" },
  { name: "FAQ's", path: "/faq" },
  { name: "Contact", path: "/contact" },
  { name: "Tech Stacks", path: "/tech-stack" },
  { name: "Ethics Policy", path: "/ethics-policy" },
 
];

export const policies = [
  { name: "Privacy Policy", path: "/privacy-policy" },
  { name: "Terms & Conditions", path: "/terms-and-conditions" },
  { name: "Refund Policy", path: "/refund-policy" },
  { name: "Modern Slavery Act", path: "/modern-slavery-act" },
  { name: "Recruitment Policy", path: "/recruitment-policy" },
  { name: "Sitemap", path: "/sitemap" },
];